helmCharts:
  - name: alloy
    repo: https://grafana.github.io/helm-charts
    version: 1.6.0
    releaseName: alloy
    namespace: grafana-alloy
    valuesFile: values.yaml

namespace: grafana-alloy