helmCharts:
  - name: mimir-distributed
    repo: https://grafana.github.io/helm-charts
    version: 6.0.5
    releaseName: mimir-distributed
    namespace: mimir
    valuesFile: values.yaml

namespace: mimir